version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    user: 1000:1000
    container_name: vaultwarden
    restart: always
    environment:
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true
      DOMAIN: ${DOMAIN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SHOW_PASSWORD_HINT: false
      LOG_LEVEL: info
    volumes:
      - ./vw-data:/data

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/vaultwarden.conf:ro
      - ./nginx/ssl/:/etc/nginx/crts/:ro
    ports:
      - "8901:443"
    command: [ nginx-debug, "-g", "daemon off;" ]

  backup:
    container_name: backup
    image: ttionya/vaultwarden-backup:latest
    restart: unless-stopped
    environment:
      RCLONE_REMOTE_NAME: 'nextcloud'
      RCLONE_REMOTE_DIR: '/00_backups/02_bitwarden/' # Your folder in nextcloud
      RCLONE_GLOBAL_FLAG: '--no-check-certificate' # Otherwise since recen versions it will not work
      CRON: '0 04 */5 * *'
      ZIP_ENABLE: 'TRUE'
      ZIP_PASSWORD: '${BACKUP_PASSWORD}'
      ZIP_TYPE: '7z'
      BACKUP_FILE_SUFFIX: '%Y-%m-%d'
      MAIL_SMTP_ENABLE: 'TRUE'
      MAIL_SMTP_VARIABLES: >
        -S smtp-use-starttls -S smtp=${SMTP_HOST} -S smtp-auth=login -S smtp-auth-user=${SMTP_USERNAME} -S smtp-auth-password=${SMTP_PASSWORD} -S from=${SMTP_USERNAME}
      MAIL_TO: ${CONFIRMATION_BACKUP_MAIL}
      MAIL_WHEN_SUCCESS: 'TRUE'
      MAIL_WHEN_FAILURE: 'TRUE'
    volumes:
      - ./vw-data:/bitwarden/data/
      - ./backup-config:/config/
